-- ============================================================
-- Node Data Política — Dados Fictícios para Demonstração
-- Cenário: Gabinete do Dep. Estadual Dr. Henrique Oliveira
-- Execute no SQL Editor do Supabase
-- ============================================================

insert into feedbacks (sender, name, message, timestamp, category, region, urgency, sentiment, topic, status, resolved_at, created_at) values

-- SEMANA 4 (mais recentes)

('5511987410023', 'Ana Paula Ferreira',
 'Bom dia! Vim aqui elogiar o deputado Henrique por ter aprovado o projeto das creches comunitárias. Nossa creche do bairro vai receber reforma, as crianças precisavam muito disso. Parabéns ao gabinete!',
 now() - interval '1 day',
 'Saúde & Educação', 'Zona Norte', 'baixa', 'positivo', 'creches comunitárias',
 'resolvido', (now() - interval '6 hours')::text,
 now() - interval '1 day'),

('5511976523301', 'Marcos Antônio Silva',
 'Preciso falar com o gabinete do deputado. Meu filho foi reprovado no ENEM e não tem vaga na escola estadual da zona sul. Já fui lá pessoalmente e disseram que não tem como. O senhor pode ajudar?',
 now() - interval '1 day 2 hours',
 'Saúde & Educação', 'Zona Sul', 'alta', 'negativo', 'falta de vagas escolas',
 'em_andamento', null,
 now() - interval '1 day 2 hours'),

('5511998234560', 'Rosimeire Nascimento',
 'Boa tarde. Sou moradora do Distrito Industrial há 23 anos. A rua principal aqui está um perigo, cheia de buracos imensos. Dois acidentes essa semana já. Precisamos urgente de recapeamento!',
 now() - interval '1 day 5 hours',
 'Infraestrutura & Obras', 'Distrito Industrial', 'alta', 'negativo', 'buracos na rua',
 'aberto', null,
 now() - interval '1 day 5 hours'),

('5511965432109', 'Cláudio Roberto Mendes',
 'Parei de acreditar em político, mas o deputado Henrique foi o único que atendeu a gente quando a fábrica da região fechou. O projeto de requalificação profissional que ele aprovou me ajudou a conseguir outro emprego. Obrigado mesmo.',
 now() - interval '2 days',
 'Desenvolvimento Econômico', 'Distrito Industrial', 'baixa', 'positivo', 'requalificação profissional',
 'resolvido', (now() - interval '1 day')::text,
 now() - interval '2 days'),

('5511943217654', 'Fernanda Lima Costa',
 'Quero saber quando vai ter audiência pública sobre o novo hospital regional. Ouvi falar que o deputado está intermediando a verba federal. Moro na zona oeste e aqui é longe demais do hospital central.',
 now() - interval '2 days 3 hours',
 'Saúde & Educação', 'Zona Oeste', 'media', 'neutro', 'hospital regional',
 'aberto', null,
 now() - interval '2 days 3 hours'),

('5511921098765', 'José Carlos Pereira',
 'Deputado, tô te mandando mensagem aqui porque a situação da segurança no Centro tá caótica. Minha loja foi assaltada pela terceira vez esse mês. A câmera de segurança pública que instalaram nem funciona. Preciso de ajuda.',
 now() - interval '2 days 6 hours',
 'Segurança Pública', 'Centro', 'alta', 'negativo', 'câmeras de segurança com defeito',
 'em_andamento', null,
 now() - interval '2 days 6 hours'),

('5511934521876', 'Patrícia Oliveira Santos',
 'Oi! Minha vizinhança tá muito feliz com o projeto de iluminação pública aprovado pelo deputado. Ficamos no escuro por dois anos aqui na zona leste. Agora com as novas luminárias a gente se sente mais segura.',
 now() - interval '3 days',
 'Segurança Pública', 'Zona Leste', 'baixa', 'positivo', 'iluminação pública',
 'resolvido', (now() - interval '2 days')::text,
 now() - interval '3 days'),

('5511956234187', 'Wanderley Souza',
 'Bom dia ao gabinete. Sou agricultor da zona rural e estou desesperado. Chuvas destruíram parte da minha lavoura e não consigo acesso ao seguro agrícola. Preciso de intermediação política urgente.',
 now() - interval '3 days 4 hours',
 'Assistência Social', 'Zona Rural', 'alta', 'negativo', 'seguro agrícola',
 'em_andamento', null,
 now() - interval '3 days 4 hours'),

('5511912876543', 'Luciana Cardoso',
 'Passando pra agradecer. A assessora do gabinete me ajudou a conseguir o BPC para minha mãe idosa. Estava tentando há 8 meses e em 15 dias com a ajuda de vocês saiu. Deus abençoe o trabalho do deputado.',
 now() - interval '3 days 8 hours',
 'Assistência Social', 'Zona Norte', 'baixa', 'positivo', 'BPC benefício idoso',
 'resolvido', (now() - interval '3 days')::text,
 now() - interval '3 days 8 hours'),

('5511987654320', 'Roberto Almeida',
 'Votei no deputado Henrique na última eleição. Mas preciso cobrar: o projeto de lei para redução das tarifas de ônibus foi engavetado? Aqui na zona sul a passagem aumentou de novo e o salário não acompanha.',
 now() - interval '4 days',
 'Transporte & Mobilidade', 'Zona Sul', 'media', 'negativo', 'tarifa de ônibus',
 'aberto', null,
 now() - interval '4 days'),

-- SEMANA 3

('5511923456781', 'Simone Rodrigues',
 'Boa tarde. Sou professora da rede estadual há 15 anos. O plano de carreira que o deputado prometeu na campanha ainda não foi votado. Os professores estão revoltados. Quando vai sair?',
 now() - interval '5 days',
 'Saúde & Educação', 'Centro', 'alta', 'negativo', 'plano de carreira professores',
 'aberto', null,
 now() - interval '5 days'),

('5511965432890', 'Edson Marcelino',
 'Moro na zona oeste, perto do rio. Toda vez que chove muito aqui alaga tudo. Perdi geladeira, sofá, cama. Já tentei contato com a prefeitura mas não resolvem. O deputado pode acionar o Estado?',
 now() - interval '5 days 6 hours',
 'Infraestrutura & Obras', 'Zona Oeste', 'alta', 'negativo', 'alagamentos recorrentes',
 'em_andamento', null,
 now() - interval '5 days 6 hours'),

('5511912345678', 'Débora Cristina Moura',
 'Queria deixar meu apoio ao deputado pela votação contra a privatização do hospital estadual. Aqui no bairro todo mundo ficou aliviado. O SUS precisa de mais defensores como ele na assembleia.',
 now() - interval '6 days',
 'Saúde & Educação', 'Zona Norte', 'baixa', 'positivo', 'defesa do SUS',
 'resolvido', (now() - interval '5 days')::text,
 now() - interval '6 days'),

('5511934218760', 'Paulo Henrique Gomes',
 'Preciso de ajuda com um caso urgente. Meu irmão está preso há 3 meses esperando julgamento por um crime que não cometeu. A defensoria pública não deu conta. Como o gabinete pode ajudar?',
 now() - interval '6 days 3 hours',
 'Segurança Pública', 'Zona Leste', 'alta', 'negativo', 'caso defensoria pública',
 'em_andamento', null,
 now() - interval '6 days 3 hours'),

('5511976234509', 'Geovana Martins',
 'Boa noite. Acabei de ver a notícia que o deputado conseguiu verba para o parque ecológico da zona rural. Que notícia boa! Precisamos preservar o que temos. Obrigada por lutar pelo meio ambiente.',
 now() - interval '7 days',
 'Meio Ambiente', 'Zona Rural', 'baixa', 'positivo', 'parque ecológico',
 'resolvido', (now() - interval '6 days')::text,
 now() - interval '7 days'),

('5511943298761', 'Rodrigo Teixeira',
 'Olá, sou empresário do setor de tecnologia. Queria propor ao deputado uma audiência para discutir incentivos fiscais para startups. Nossa cidade tem potencial mas a legislação estadual trava muito.',
 now() - interval '7 days 2 hours',
 'Desenvolvimento Econômico', 'Centro', 'media', 'neutro', 'incentivos fiscais startups',
 'aberto', null,
 now() - interval '7 days 2 hours'),

('5511921876540', 'Maria das Graças',
 'Deputado, o ônibus da minha linha foi cortado semana passada. Preciso pegar 3 conduções pra chegar no serviço agora. Trabalho no distrito industrial e fico esperando na chuva. Isso não pode continuar.',
 now() - interval '8 days',
 'Transporte & Mobilidade', 'Zona Norte', 'alta', 'negativo', 'linha de ônibus cortada',
 'em_andamento', null,
 now() - interval '8 days'),

('5511956781234', 'Antônio Carlos Ferreira',
 'Boa tarde. Represento a associação de moradores da zona sul. Temos 200 famílias sem regularização fundiária há 12 anos. O projeto de usucapião coletivo que o deputado apresentou é nossa esperança. Quando vai a votação?',
 now() - interval '8 days 4 hours',
 'Assistência Social', 'Zona Sul', 'alta', 'neutro', 'regularização fundiária',
 'aberto', null,
 now() - interval '8 days 4 hours'),

('5511998765430', 'Juliana Freitas',
 'Passei na UBS do meu bairro ontem e estava fechada de novo, sem médico. Segunda vez esse mês. Sou diabética e preciso de acompanhamento regular. Alguém pode fazer alguma coisa? Zona oeste esquecida.',
 now() - interval '9 days',
 'Saúde & Educação', 'Zona Oeste', 'alta', 'negativo', 'UBS fechada sem médico',
 'em_andamento', null,
 now() - interval '9 days'),

('5511934512876', 'Nelson Barbosa',
 'Quero registrar meu agradecimento. A obra da ponte da estrada rural que estava interditada há 2 anos finalmente foi licitada com emenda do deputado Henrique. Os produtores rurais agradecem muito.',
 now() - interval '9 days 6 hours',
 'Infraestrutura & Obras', 'Zona Rural', 'baixa', 'positivo', 'ponte rural recuperada',
 'resolvido', (now() - interval '8 days')::text,
 now() - interval '9 days 6 hours'),

-- SEMANA 2

('5511965432801', 'Cristiane Aparecida',
 'Oi, estou tentando denunciar o descarte irregular de lixo industrial na área verde da zona leste. Já liguei no 156 da prefeitura três vezes e nada. Isso está poluindo o córrego que passa perto das casas.',
 now() - interval '10 days',
 'Meio Ambiente', 'Zona Leste', 'alta', 'negativo', 'poluição córrego lixo industrial',
 'em_andamento', null,
 now() - interval '10 days'),

('5511912345601', 'Fabiano Motta',
 'Deputado votou contra o corte no fundo de manutenção das estradas vicinais. Agricultor aqui do interior agradece. Quando chove não conseguia nem levar a produção pra cidade. Voto confirmado nas próximas eleições.',
 now() - interval '11 days',
 'Infraestrutura & Obras', 'Zona Rural', 'baixa', 'positivo', 'estradas vicinais',
 'resolvido', (now() - interval '10 days')::text,
 now() - interval '11 days'),

('5511976543219', 'Adriana Conceição',
 'Meu filho de 16 anos foi abordado violentamente por policiais sem motivo aqui no Centro. Ele estava só andando na rua. Quero saber se o deputado apoia projetos de controle externo da polícia.',
 now() - interval '11 days 3 hours',
 'Segurança Pública', 'Centro', 'alta', 'negativo', 'abuso policial',
 'aberto', null,
 now() - interval '11 days 3 hours'),

('5511943218760', 'Leandro Costa',
 'Bom dia. Sou coordenador de uma ONG de reciclagem na zona norte. Soubemos que o deputado está articulando um projeto de economia circular no estado. Gostaríamos de contribuir com nossa experiência prática.',
 now() - interval '12 days',
 'Meio Ambiente', 'Zona Norte', 'media', 'positivo', 'economia circular reciclagem',
 'aberto', null,
 now() - interval '12 days'),

('5511921765430', 'Sônia Lúcia',
 'Já faz 6 meses que pedi ao INSS a aposentadoria por invalidez e está parado. Tenho laudo médico, tudo certo. Minha família depende disso pra sobreviver. O gabinete do deputado pode ajudar com ofício?',
 now() - interval '12 days 5 hours',
 'Assistência Social', 'Zona Sul', 'alta', 'negativo', 'aposentadoria por invalidez INSS',
 'em_andamento', null,
 now() - interval '12 days 5 hours'),

('5511956234809', 'Tiago Mendonça',
 'Passando pra reclamar do caos no trânsito da avenida principal do Centro. Obras há 4 meses sem previsão de término. O desvio de tráfego está destruindo as ruas residenciais. Quando termina isso?',
 now() - interval '13 days',
 'Transporte & Mobilidade', 'Centro', 'media', 'negativo', 'obras sem prazo trânsito',
 'aberto', null,
 now() - interval '13 days'),

('5511987651234', 'Eliana Borges',
 'O projeto do deputado pra regularizar as feiras livres foi aprovado! Sou feirante há 20 anos e finalmente vou poder ter meu CNPJ e emitir nota. Isso muda tudo pra nós. Obrigada de coração.',
 now() - interval '13 days 4 hours',
 'Desenvolvimento Econômico', 'Zona Sul', 'baixa', 'positivo', 'regularização feiras livres',
 'resolvido', (now() - interval '12 days')::text,
 now() - interval '13 days 4 hours'),

('5511965430987', 'Maurício Pinheiro',
 'Bom dia. Represento o sindicato dos metalúrgicos. A fábrica onde trabalhamos ameaça fechar dizendo que não consegue competir. Queremos audiência com o deputado pra discutir política industrial estadual.',
 now() - interval '14 days',
 'Desenvolvimento Econômico', 'Distrito Industrial', 'alta', 'negativo', 'risco fechamento fábrica',
 'em_andamento', null,
 now() - interval '14 days'),

-- SEMANA 1 (mais antigas)

('5511934217650', 'Vanessa Duarte',
 'Boa tarde! Fui à inauguração da quadra esportiva que o deputado conseguiu verba. A molecada do bairro ficou muito feliz. Era um terreno abandonado que virou ponto de droga. Agora é lazer. Parabéns!',
 now() - interval '15 days',
 'Assistência Social', 'Zona Leste', 'baixa', 'positivo', 'quadra esportiva inaugurada',
 'resolvido', (now() - interval '14 days')::text,
 now() - interval '15 days'),

('5511912876501', 'Wagner Santos',
 'Preciso de ajuda urgente. Minha casa foi notificada pela prefeitura para demolição por risco, mas é minha única moradia. Não tenho pra onde ir com 4 filhos. Preciso de assistência social e orientação jurídica.',
 now() - interval '15 days 6 hours',
 'Assistência Social', 'Zona Norte', 'alta', 'negativo', 'habitação risco demolição',
 'em_andamento', null,
 now() - interval '15 days 6 hours'),

('5511976543210', 'Carla Magalhães',
 'Oi gabinete. Sou médica do CAPS e quero parabenizar o deputado pela emenda que garantiu custeio da saúde mental. Nosso serviço estava perto de fechar por falta de recursos. Pacientes em tratamento agradecem.',
 now() - interval '16 days',
 'Saúde & Educação', 'Centro', 'baixa', 'positivo', 'saúde mental CAPS',
 'resolvido', (now() - interval '15 days')::text,
 now() - interval '16 days'),

('5511943218709', 'Gilberto Araújo',
 'Já tentei 5 vezes fazer exame de colonoscopia pelo SUS. Fila enorme. Tenho histórico familiar de câncer de intestino. O plano de saúde não cobre. Preciso de ajuda pra conseguir esse exame urgente.',
 now() - interval '16 days 4 hours',
 'Saúde & Educação', 'Zona Oeste', 'alta', 'negativo', 'fila exame SUS',
 'em_andamento', null,
 now() - interval '16 days 4 hours'),

('5511921876503', 'Renata Figueiredo',
 'Quero denunciar desmatamento ilegal na área de preservação da zona rural. Vi máquinas trabalhando no final de semana. Tirei fotos e vídeos. Como envio para o gabinete? O deputado precisa saber disso.',
 now() - interval '17 days',
 'Meio Ambiente', 'Zona Rural', 'alta', 'negativo', 'desmatamento ilegal',
 'em_andamento', null,
 now() - interval '17 days'),

('5511956234801', 'Hélio Castilho',
 'Bom dia. Sou dono de padaria no distrito industrial. Com o projeto aprovado pelo deputado pra simplificação do alvará de funcionamento, economizei 4 meses de burocracia. Isso faz diferença pra pequenos negócios.',
 now() - interval '18 days',
 'Desenvolvimento Econômico', 'Distrito Industrial', 'baixa', 'positivo', 'simplificação alvará',
 'resolvido', (now() - interval '17 days')::text,
 now() - interval '18 days'),

('5511987654301', 'Ivone Cavalcanti',
 'Boa tarde ao gabinete do deputado. Moro na zona norte e o ponto de ônibus mais próximo fica a 1,5km de casa. Idosa, não consigo caminhar essa distância. Precisa de mais cobertura de transporte aqui.',
 now() - interval '18 days 4 hours',
 'Transporte & Mobilidade', 'Zona Norte', 'media', 'negativo', 'ponto de ônibus distante',
 'aberto', null,
 now() - interval '18 days 4 hours'),

('5511965430981', 'Bruno Lacerda',
 'Mandando mensagem pra agradecer o deputado pela audiência sobre segurança nas escolas. Sou diretor de escola estadual e a situação de violência está preocupante. O projeto de câmeras e segurança escolar era urgente.',
 now() - interval '19 days',
 'Segurança Pública', 'Zona Sul', 'baixa', 'positivo', 'segurança escolar',
 'resolvido', (now() - interval '18 days')::text,
 now() - interval '19 days'),

('5511934218709', 'Alessandra Vieira',
 'Olá. Tenho uma filha com autismo e estou há 2 anos na fila por vaga na escola especial estadual. Já falei com a secretaria e nada. O deputado pode interceder? Minha filha tem direito à educação inclusiva.',
 now() - interval '20 days',
 'Saúde & Educação', 'Zona Leste', 'alta', 'negativo', 'vaga escola especial autismo',
 'em_andamento', null,
 now() - interval '20 days'),

('5511912345609', 'Valdeci Nogueira',
 'Boa noite. Fui ao evento do gabinete itinerante na zona rural e saí de lá com tudo resolvido: cadastro no CadÚnico atualizado, encaminhamento pro CRAS e orientação sobre aposentadoria rural. Serviço excelente.',
 now() - interval '21 days',
 'Assistência Social', 'Zona Rural', 'baixa', 'positivo', 'gabinete itinerante zona rural',
 'resolvido', (now() - interval '20 days')::text,
 now() - interval '21 days'),

('5511976543201', 'Marcelo Borba',
 'Deputado, o projeto de lei que o senhor apresentou sobre energia solar em condomínios populares é ótimo na teoria. Mas aqui na zona oeste os condomínios não têm dinheiro pra implantação inicial. Precisa de financiamento.',
 now() - interval '22 days',
 'Meio Ambiente', 'Zona Oeste', 'media', 'neutro', 'energia solar condomínios',
 'aberto', null,
 now() - interval '22 days'),

('5511943218701', 'Cíntia Barbosa',
 'Quero denunciar que a empresa de transporte escolar do município está cobrando dos pais de alunos da zona rural. Isso é gratuito por lei! Meu filho usa e cobraram R$ 80 por mês. Absurdo.',
 now() - interval '23 days',
 'Transporte & Mobilidade', 'Zona Rural', 'alta', 'negativo', 'cobrança ilegal transporte escolar',
 'em_andamento', null,
 now() - interval '23 days'),

('5511921765409', 'Fábio Santana',
 'Quero parabenizar a iniciativa do deputado de criar o observatório de preços no estado. Desde que começou a divulgar as comparações, os postos de gasolina da zona sul baixaram os preços. Transparência funciona.',
 now() - interval '24 days',
 'Propostas & Projetos', 'Zona Sul', 'baixa', 'positivo', 'observatório de preços',
 'resolvido', (now() - interval '23 days')::text,
 now() - interval '24 days'),

('5511956234809', 'Norma Albuquerque',
 'Boa tarde. Sou técnica de enfermagem do hospital regional. Estamos há 4 meses sem reajuste e trabalhando com equipamentos quebrados. A situação é crítica. O deputado pode acionar o governo estadual?',
 now() - interval '25 days',
 'Saúde & Educação', 'Centro', 'alta', 'negativo', 'equipamentos hospitalares quebrados',
 'aberto', null,
 now() - interval '25 days'),

('5511987654312', 'Sebastião Rocha',
 'Senhor deputado, sou fazendeiro da zona rural. Com o apoio do gabinete conseguimos aprovar o projeto de irrigação coletiva. Nossa produção aumentou 40% esse ano. Deus abençoe esse trabalho.',
 now() - interval '26 days',
 'Desenvolvimento Econômico', 'Zona Rural', 'baixa', 'positivo', 'projeto irrigação rural',
 'resolvido', (now() - interval '25 days')::text,
 now() - interval '26 days'),

('5511965432812', 'Tatiana Campos',
 'Olá, sou mãe de três filhos e moro no conjunto habitacional da zona leste. A praça do conjunto foi prometida há 5 anos e até hoje é um terreno baldio com esgoto a céu aberto. Crianças brincam ali. É perigoso.',
 now() - interval '27 days',
 'Infraestrutura & Obras', 'Zona Leste', 'media', 'negativo', 'praça prometida não construída',
 'aberto', null,
 now() - interval '27 days'),

('5511934218712', 'Ricardo Melo',
 'Bom dia. Vi no jornal que o deputado vai propor CPI para investigar os contratos de merenda escolar. Apoio total. Meu filho estuda na rede estadual e a merenda é péssima. Isso precisa ser investigado.',
 now() - interval '28 days',
 'Propostas & Projetos', 'Zona Norte', 'media', 'positivo', 'CPI merenda escolar',
 'aberto', null,
 now() - interval '28 days'),

('5511912345612', 'Emília Corrêa',
 'Passei para registrar que meu marido conseguiu o emprego pela parceria da assembleia com o SENAI. O curso de elétrica foi de graça e em 3 meses ele já estava contratado. Família agradecida.',
 now() - interval '29 days',
 'Desenvolvimento Econômico', 'Zona Oeste', 'baixa', 'positivo', 'parceria SENAI emprego',
 'resolvido', (now() - interval '28 days')::text,
 now() - interval '29 days'),

('5511976543212', 'Dirceu Fonseca',
 'Boa tarde. Sou presidente do conselho comunitário da zona norte. Queremos propor ao deputado a criação de um polo logístico no nosso bairro pra gerar emprego. Temos terreno público ocioso disponível há anos.',
 now() - interval '29 days 6 hours',
 'Desenvolvimento Econômico', 'Zona Norte', 'media', 'neutro', 'polo logístico terreno público',
 'aberto', null,
 now() - interval '29 days 6 hours'),

('5511943218714', 'Sandra Mello',
 'Minha filha sofreu acidente na ciclovia da zona sul que está toda quebrada. Levou pontos na cabeça. Já fotografei vários trechos perigosos. Isso é crime de responsabilidade. O deputado pode cobrar o DER?',
 now() - interval '30 days',
 'Infraestrutura & Obras', 'Zona Sul', 'alta', 'negativo', 'ciclovia perigosa acidente',
 'em_andamento', null,
 now() - interval '30 days');
