-- ============================================================
-- Node Data Política — Feedbacks Fictícios
-- Político: Dep. Matheus Braga
-- Execute no SQL Editor do Supabase (politicas.nodedata.com.br)
-- ============================================================

insert into feedbacks (sender, name, message, timestamp, category, region, urgency, sentiment, topic, status, resolved_at, created_at) values

('5521987410023', 'Ana Paula Ferreira',
 'Bom dia! Quero agradecer ao deputado Matheus Braga pela aprovação do projeto das creches comunitárias. Nossa creche do bairro vai receber reforma urgente. As crianças precisavam muito disso. Parabéns!',
 now() - interval '1 day',
 'Saúde & Educação', 'Zona Norte', 'baixa', 'positivo', 'creches comunitárias aprovadas',
 'resolvido', (now() - interval '12 hours')::text, now() - interval '1 day'),

('5521976523301', 'Marcos Antônio Silva',
 'Deputado Matheus, meu filho terminou o ensino médio e não consegue vaga em curso técnico pelo estado. Lista de espera tem 400 pessoas. Isso é descaso com a juventude. O senhor pode resolver isso?',
 now() - interval '1 day 3 hours',
 'Saúde & Educação', 'Zona Sul', 'alta', 'negativo', 'falta de vagas curso técnico',
 'em_andamento', null, now() - interval '1 day 3 hours'),

('5521998234560', 'Rosimeire Nascimento',
 'Rua das Acácias no Distrito Industrial está intransitável. Buracos enormes, já quebraram 3 carros essa semana. Moro aqui há 20 anos e nunca vi tão abandonado. Matheus Braga precisa ver isso!',
 now() - interval '1 day 6 hours',
 'Infraestrutura & Obras', 'Distrito Industrial', 'alta', 'negativo', 'rua destruída sem manutenção',
 'aberto', null, now() - interval '1 day 6 hours'),

('5521965432109', 'Cláudio Roberto Mendes',
 'O deputado Matheus Braga foi o único que apareceu quando a fábrica da região fechou. O projeto de requalificação profissional que ele aprovou me ajudou a conseguir outro emprego em 2 meses. Gratidão.',
 now() - interval '2 days',
 'Desenvolvimento Econômico', 'Distrito Industrial', 'baixa', 'positivo', 'requalificação profissional funcionou',
 'resolvido', (now() - interval '1 day')::text, now() - interval '2 days'),

('5521943217654', 'Fernanda Lima',
 'Deputado, quando vai ter audiência pública sobre o hospital regional? Aqui na zona oeste a gente percorre 40km para chegar no hospital central. Ouvi que o Matheus Braga está conseguindo verba federal. Quando sai?',
 now() - interval '2 days 4 hours',
 'Saúde & Educação', 'Zona Oeste', 'media', 'neutro', 'hospital regional zona oeste',
 'aberto', null, now() - interval '2 days 4 hours'),

('5521921098765', 'José Carlos Pereira',
 'Matheus, minha loja no centro foi assaltada pela quarta vez esse mês. A câmera de segurança pública instalada há 2 anos nunca funcionou. Paguei impostos a vida inteira pra isso? Me ajuda.',
 now() - interval '2 days 8 hours',
 'Segurança Pública', 'Centro', 'alta', 'negativo', 'câmeras de segurança defeituosas',
 'em_andamento', null, now() - interval '2 days 8 hours'),

('5521934521876', 'Patrícia Oliveira',
 'Que alegria! Projeto de iluminação pública do deputado Matheus Braga finalmente foi executado aqui na zona leste. Ficamos 3 anos no escuro. Agora as crianças podem brincar na rua com mais segurança. Obrigada!',
 now() - interval '3 days',
 'Segurança Pública', 'Zona Leste', 'baixa', 'positivo', 'iluminação pública instalada',
 'resolvido', (now() - interval '2 days')::text, now() - interval '3 days'),

('5521956234187', 'Wanderley Souza',
 'Sou produtor rural e estou no desespero. As chuvas de janeiro destruíram minha lavoura de feijão inteira. Fui ao banco e não consigo o seguro agrícola porque o cadastro está desatualizado no sistema do Estado. Matheus pode ajudar?',
 now() - interval '3 days 5 hours',
 'Assistência Social', 'Zona Rural', 'alta', 'negativo', 'seguro agrícola bloqueado',
 'em_andamento', null, now() - interval '3 days 5 hours'),

('5521912876543', 'Luciana Cardoso',
 'Boa tarde! Quero agradecer ao gabinete do Matheus Braga. A assessora Camila me ajudou a conseguir o BPC pra minha mãe de 78 anos. Tentei 9 meses sozinha e em 20 dias vocês resolveram. Que equipe incrível.',
 now() - interval '3 days 9 hours',
 'Assistência Social', 'Zona Norte', 'baixa', 'positivo', 'BPC conquistado para idosa',
 'resolvido', (now() - interval '3 days')::text, now() - interval '3 days 9 hours'),

('5521987654320', 'Roberto Almeida',
 'Votei no Matheus Braga acreditando na redução da tarifa de ônibus. Já faz 2 anos de mandato e a passagem só subiu. Aqui na zona sul a gente gasta R$400 por mês só de transporte. Cadê a promessa?',
 now() - interval '4 days',
 'Transporte & Mobilidade', 'Zona Sul', 'media', 'negativo', 'promessa tarifa ônibus não cumprida',
 'aberto', null, now() - interval '4 days'),

('5521923456781', 'Simone Rodrigues',
 'Sou professora há 18 anos na rede estadual. O plano de carreira que o deputado Matheus prometeu na campanha continua engavetado na assembleia. Os professores estão fazendo hora extra sem remuneração. Vergonhoso.',
 now() - interval '5 days',
 'Saúde & Educação', 'Centro', 'alta', 'negativo', 'plano de carreira professores parado',
 'aberto', null, now() - interval '5 days'),

('5521965432890', 'Edson Marcelino',
 'Deputado Matheus Braga, moro às margens do Córrego do Meio na zona oeste. Todo dezembro alaga e eu perco tudo. Geladeira, colchão, móveis. A obra de contenção foi prometida em 2022. Quando vai sair?',
 now() - interval '5 days 7 hours',
 'Infraestrutura & Obras', 'Zona Oeste', 'alta', 'negativo', 'alagamento recorrente sem obra',
 'em_andamento', null, now() - interval '5 days 7 hours'),

('5521912345678', 'Débora Cristina',
 'Quero registrar apoio ao deputado Matheus Braga pela votação contra a privatização do hospital estadual Santa Casa. Aqui no bairro todo mundo ficou aliviado. Continue defendendo o SUS com essa força!',
 now() - interval '6 days',
 'Saúde & Educação', 'Zona Norte', 'baixa', 'positivo', 'voto contra privatização hospital',
 'resolvido', (now() - interval '5 days')::text, now() - interval '6 days'),

('5521934218760', 'Paulo Henrique',
 'Deputado, meu irmão Leandro está preso na cadeia pública há 5 meses aguardando julgamento por um crime que não cometeu. A defensoria pública disse que a fila de processos é enorme. O gabinete pode interceder?',
 now() - interval '6 days 4 hours',
 'Segurança Pública', 'Zona Leste', 'alta', 'negativo', 'preso aguardando julgamento injusto',
 'em_andamento', null, now() - interval '6 days 4 hours'),

('5521976234509', 'Geovana Martins',
 'Vi no jornal que o Matheus Braga conseguiu R$2 milhões para o parque ecológico da zona rural. Isso é muito importante! Estamos vendo o desmatamento avançar aqui. Obrigada por lutar pelo meio ambiente.',
 now() - interval '7 days',
 'Meio Ambiente', 'Zona Rural', 'baixa', 'positivo', 'verba parque ecológico aprovada',
 'resolvido', (now() - interval '6 days')::text, now() - interval '7 days'),

('5521943298761', 'Rodrigo Teixeira',
 'Bom dia. Sou empresário de tecnologia aqui da cidade. Queria uma reunião com o deputado Matheus Braga para discutir incentivos fiscais para startups. A legislação estadual atual afasta investimentos. Podemos marcar?',
 now() - interval '7 days 3 hours',
 'Desenvolvimento Econômico', 'Centro', 'media', 'neutro', 'incentivos fiscais startups',
 'aberto', null, now() - interval '7 days 3 hours'),

('5521921876540', 'Maria das Graças',
 'Matheus Braga! Cortaram a linha 47 de ônibus que passava pela minha rua. Agora tenho que andar 2km até o próximo ponto, com 60 anos e problema no joelho. Trabalho no distrito industrial. Me ajuda por favor.',
 now() - interval '8 days',
 'Transporte & Mobilidade', 'Zona Norte', 'alta', 'negativo', 'linha de ônibus cortada',
 'em_andamento', null, now() - interval '8 days'),

('5521956781234', 'Antônio Carlos',
 'Represento 240 famílias do Conjunto Esperança na zona sul. Estamos sem regularização fundiária há 14 anos. O projeto de usucapião coletivo que o Matheus apresentou é nossa única esperança. Quando vai a plenário?',
 now() - interval '8 days 5 hours',
 'Assistência Social', 'Zona Sul', 'alta', 'neutro', 'regularização fundiária 240 famílias',
 'aberto', null, now() - interval '8 days 5 hours'),

('5521998765430', 'Juliana Freitas',
 'UBS do Jardim Primavera fechou de novo sem médico. Terceira vez em 30 dias. Sou diabética tipo 1 e preciso de acompanhamento semanal. Vivo a 12km do hospital central. Matheus Braga precisa resolver isso urgente.',
 now() - interval '9 days',
 'Saúde & Educação', 'Zona Oeste', 'alta', 'negativo', 'UBS fechada sem médico recorrente',
 'em_andamento', null, now() - interval '9 days'),

('5521934512876', 'Nelson Barbosa',
 'Que boa notícia! A ponte da Estrada Municipal 340 que estava interditada há 3 anos finalmente foi licitada com emenda do deputado Matheus Braga. Os produtores rurais conseguiam escoar a produção. Muito obrigado!',
 now() - interval '9 days 7 hours',
 'Infraestrutura & Obras', 'Zona Rural', 'baixa', 'positivo', 'ponte rural licitada com emenda',
 'resolvido', (now() - interval '8 days')::text, now() - interval '9 days 7 hours'),

('5521965432801', 'Cristiane Aparecida',
 'Denúncia urgente para o gabinete do Matheus Braga: empresa está despejando resíduo industrial no Córrego das Pedras na zona leste. Já liguei para o 156 quatro vezes e o caminhão continua aparecendo todo domingo de madrugada.',
 now() - interval '10 days',
 'Meio Ambiente', 'Zona Leste', 'alta', 'negativo', 'descarte ilegal resíduo industrial',
 'em_andamento', null, now() - interval '10 days'),

('5521912345601', 'Fabiano Motta',
 'Matheus Braga votou contra o corte de 30% no fundo das estradas vicinais. Sou agricultor e se cortar esse fundo a gente não consegue mais levar a produção pra cidade depois da chuva. Voto garantido no próximo pleito.',
 now() - interval '11 days',
 'Infraestrutura & Obras', 'Zona Rural', 'baixa', 'positivo', 'voto contra corte estradas vicinais',
 'resolvido', (now() - interval '10 days')::text, now() - interval '11 days'),

('5521976543219', 'Adriana Conceição',
 'Deputado Matheus, meu filho de 17 anos foi abordado com violência por PMs na saída da escola aqui no Centro sem motivo nenhum. Ele levou um soco. Existe projeto de câmeras corporais que o senhor apoia? Queremos justiça.',
 now() - interval '11 days 4 hours',
 'Segurança Pública', 'Centro', 'alta', 'negativo', 'violência policial contra jovem',
 'aberto', null, now() - interval '11 days 4 hours'),

('5521943218760', 'Leandro Costa',
 'Bom dia deputado Matheus Braga! Coordeno uma ONG de reciclagem com 80 catadores na zona norte. Soubemos do projeto de economia circular que o senhor está articulando. Podemos contribuir com dados e experiência real.',
 now() - interval '12 days',
 'Meio Ambiente', 'Zona Norte', 'media', 'positivo', 'ONG quer apoiar projeto economia circular',
 'aberto', null, now() - interval '12 days'),

('5521921765430', 'Sônia Lúcia',
 'Há 7 meses dando entrada na aposentadoria por invalidez no INSS e não sai. Tenho laudo do neurologista, perícia feita, tudo certo no sistema. Minha família está sem renda. O gabinete do Matheus pode protocolar um ofício?',
 now() - interval '12 days 6 hours',
 'Assistência Social', 'Zona Sul', 'alta', 'negativo', 'aposentadoria invalidez INSS travada',
 'em_andamento', null, now() - interval '12 days 6 hours'),

('5521956234809', 'Tiago Mendonça',
 'Matheus Braga, a Avenida Brasil no Centro está em obras há 5 meses e ninguém sabe quando termina. O desvio pelo bairro Santa Cruz destruiu as ruas residenciais que eram de paralelepípedo antigo. Quem vai pagar isso?',
 now() - interval '13 days',
 'Transporte & Mobilidade', 'Centro', 'media', 'negativo', 'obras sem prazo destroem ruas',
 'aberto', null, now() - interval '13 days'),

('5521987651234', 'Eliana Borges',
 'Deputado, o projeto de regularização das feiras livres que o Matheus aprovou mudou minha vida! Sou feirante há 22 anos, agora tenho CNPJ, emito nota fiscal e consigo crédito no banco. Isso é inclusão de verdade.',
 now() - interval '13 days 5 hours',
 'Desenvolvimento Econômico', 'Zona Sul', 'baixa', 'positivo', 'regularização feiras livres aprovada',
 'resolvido', (now() - interval '12 days')::text, now() - interval '13 days 5 hours'),

('5521965430987', 'Maurício Pinheiro',
 'Sou representante do sindicato dos metalúrgicos. A Metalúrgica Branco vai fechar as portas em março, 320 funcionários na rua. Pedimos urgência numa reunião com o deputado Matheus Braga para discutir política industrial.',
 now() - interval '14 days',
 'Desenvolvimento Econômico', 'Distrito Industrial', 'alta', 'negativo', 'fábrica ameaça fechar 320 empregos',
 'em_andamento', null, now() - interval '14 days'),

('5521934217650', 'Vanessa Duarte',
 'Fui à inauguração da quadra poliesportiva que o deputado Matheus Braga conseguiu verba. Era um terreno abandonado que virou ponto de tráfico há anos. Agora virou espaço de lazer. A comunidade está muito feliz!',
 now() - interval '15 days',
 'Assistência Social', 'Zona Leste', 'baixa', 'positivo', 'quadra esportiva revitalizou área de risco',
 'resolvido', (now() - interval '14 days')::text, now() - interval '15 days'),

('5521912876501', 'Wagner Santos',
 'Preciso de ajuda urgente. Recebi notificação da prefeitura para demolição da minha casa por risco de deslizamento. É a única moradia que tenho, comprada com 20 anos de economia. Tenho 4 filhos. O Matheus pode me ajudar?',
 now() - interval '15 days 7 hours',
 'Assistência Social', 'Zona Norte', 'alta', 'negativo', 'casa notificada para demolição',
 'em_andamento', null, now() - interval '15 days 7 hours'),

('5521976543210', 'Carla Magalhães',
 'Sou psiquiatra do CAPS e preciso agradecer ao deputado Matheus Braga. A emenda parlamentar que ele destinou para custeio da saúde mental salvou nosso serviço do fechamento. 380 pacientes em tratamento continuam sendo atendidos.',
 now() - interval '16 days',
 'Saúde & Educação', 'Centro', 'baixa', 'positivo', 'emenda salva CAPS do fechamento',
 'resolvido', (now() - interval '15 days')::text, now() - interval '16 days'),

('5521943218709', 'Gilberto Araújo',
 'Já marquei 6 consultas pelo SUS para fazer colonoscopia e todas foram canceladas. Tenho histórico de câncer colorretal na família. Meu médico diz que precisa urgente. Matheus Braga pode conseguir uma vaga?',
 now() - interval '16 days 5 hours',
 'Saúde & Educação', 'Zona Oeste', 'alta', 'negativo', 'consulta especialista SUS cancelada',
 'em_andamento', null, now() - interval '16 days 5 hours'),

('5521921876503', 'Renata Figueiredo',
 'Deputado Matheus Braga, estou denunciando desmatamento ilegal na APP do Rio Claro na zona rural. Vi tratores na semana passada abrindo estrada em área de proteção. Tenho vídeos. Como envio ao gabinete?',
 now() - interval '17 days',
 'Meio Ambiente', 'Zona Rural', 'alta', 'negativo', 'desmatamento APP Rio Claro',
 'em_andamento', null, now() - interval '17 days'),

('5521956234801', 'Hélio Castilho',
 'Bom dia! Sou dono de padaria aqui no Distrito Industrial. Com o projeto do deputado Matheus Braga que simplificou o alvará de funcionamento, economizei 4 meses de burocracia e R$1.200 em taxas. Isso ajuda o pequeno empresário.',
 now() - interval '18 days',
 'Desenvolvimento Econômico', 'Distrito Industrial', 'baixa', 'positivo', 'alvará simplificado economizou tempo',
 'resolvido', (now() - interval '17 days')::text, now() - interval '18 days'),

('5521987654301', 'Ivone Cavalcanti',
 'Deputado Matheus, sou aposentada de 67 anos na zona norte. O ponto de ônibus mais próximo fica a quase 2km de casa. Tenho artrose nos dois joelhos. Com a chuva então é impossível. Precisa de mais cobertura aqui.',
 now() - interval '18 days 5 hours',
 'Transporte & Mobilidade', 'Zona Norte', 'media', 'negativo', 'idosa sem acesso a transporte',
 'aberto', null, now() - interval '18 days 5 hours'),

('5521965430981', 'Bruno Lacerda',
 'Sou diretor da Escola Estadual João XXIII. Agradeço ao deputado Matheus Braga pela audiência sobre segurança escolar. O projeto de instalação de câmeras e contratação de agentes foi aprovado. Reduzimos os incidentes em 60%.',
 now() - interval '19 days',
 'Segurança Pública', 'Zona Sul', 'baixa', 'positivo', 'câmeras escolares reduziram violência',
 'resolvido', (now() - interval '18 days')::text, now() - interval '19 days'),

('5521934218759', 'Alessandra Vieira',
 'Minha filha Maria Clara tem autismo nível 2 e está há 3 anos na fila para vaga na APAE estadual. Já fui à secretaria de educação, já mandei carta. O deputado Matheus Braga pode interceder? Ela tem direito constitucional.',
 now() - interval '20 days',
 'Saúde & Educação', 'Zona Leste', 'alta', 'negativo', 'fila APAE 3 anos criança autista',
 'em_andamento', null, now() - interval '20 days'),

('5521912345600', 'Valdeci Nogueira',
 'Participei do gabinete itinerante do Matheus Braga aqui na zona rural. Em um único dia resolvi o cadastro no CadÚnico, o encaminhamento pro CRAS e a orientação sobre aposentadoria rural. Que iniciativa importante!',
 now() - interval '21 days',
 'Assistência Social', 'Zona Rural', 'baixa', 'positivo', 'gabinete itinerante resolveu tudo',
 'resolvido', (now() - interval '20 days')::text, now() - interval '21 days'),

('5521976543200', 'Marcelo Borba',
 'Matheus Braga, o projeto de energia solar nos condomínios populares é ótimo. Mas aqui no condomínio Jardim das Flores na zona oeste ninguém tem os R$8 mil de entrada para instalar. Precisa de linha de financiamento junto.',
 now() - interval '22 days',
 'Meio Ambiente', 'Zona Oeste', 'media', 'neutro', 'energia solar sem financiamento popular',
 'aberto', null, now() - interval '22 days'),

('5521943218700', 'Cíntia Barbosa',
 'Denúncia para o gabinete do Matheus Braga: empresa de transporte escolar está cobrando R$90 por mês das famílias da zona rural. O serviço é gratuito por lei! Tenho print do boleto que mandaram. Isso precisa ser investigado.',
 now() - interval '23 days',
 'Transporte & Mobilidade', 'Zona Rural', 'alta', 'negativo', 'cobrança ilegal transporte escolar',
 'em_andamento', null, now() - interval '23 days'),

('5521921765408', 'Fábio Santana',
 'O observatório de preços criado pelo deputado Matheus Braga está funcionando! Depois que começou a publicar as comparações semanais, o supermercado Bom Preço baixou o preço do arroz e do óleo. Transparência gera resultado.',
 now() - interval '24 days',
 'Propostas & Projetos', 'Zona Sul', 'baixa', 'positivo', 'observatório preços gerou resultado',
 'resolvido', (now() - interval '23 days')::text, now() - interval '24 days'),

('5521956234808', 'Norma Albuquerque',
 'Sou técnica de enfermagem do Hospital Regional há 12 anos. Estamos 5 meses sem reajuste de salário. Os equipamentos do centro cirúrgico estão quebrando e não tem peça. O Matheus Braga pode pressionar o governo estadual?',
 now() - interval '25 days',
 'Saúde & Educação', 'Centro', 'alta', 'negativo', 'hospital sem reajuste equipamentos quebrados',
 'aberto', null, now() - interval '25 days'),

('5521987654311', 'Sebastião Rocha',
 'Deputado Matheus Braga, sou produtor de café aqui da zona rural. O projeto de irrigação coletiva que o senhor aprovou foi um divisor de águas. Nossa cooperativa produziu 35% a mais essa safra. Isso é política pública real.',
 now() - interval '26 days',
 'Desenvolvimento Econômico', 'Zona Rural', 'baixa', 'positivo', 'irrigação coletiva aumentou produção',
 'resolvido', (now() - interval '25 days')::text, now() - interval '26 days'),

('5521965432811', 'Tatiana Campos',
 'Matheus Braga, no Conjunto Habitacional Nova Esperança na zona leste a praça foi prometida há 6 anos. Hoje é um terreno com esgoto a céu aberto onde as crianças brincam porque não tem outro lugar. Quando vai ser construída?',
 now() - interval '27 days',
 'Infraestrutura & Obras', 'Zona Leste', 'media', 'negativo', 'praça prometida 6 anos sem obra',
 'aberto', null, now() - interval '27 days'),

('5521934218711', 'Ricardo Melo',
 'Matheus Braga vai propor CPI para investigar desvios na merenda escolar? Meu filho estuda na rede estadual e a comida que chega é péssima, quantidade menor do que deveria. Tem denúncia de superfaturamento no contrato.',
 now() - interval '28 days',
 'Propostas & Projetos', 'Zona Norte', 'media', 'positivo', 'CPI merenda escolar necessária',
 'aberto', null, now() - interval '28 days'),

('5521912345611', 'Emília Corrêa',
 'Boa tarde! Vim agradecer pessoalmente ao deputado Matheus Braga. Meu marido estava desempregado há 14 meses. Participou do curso de manutenção elétrica pela parceria com o SENAI e foi contratado em 6 semanas. Que impacto real!',
 now() - interval '29 days',
 'Desenvolvimento Econômico', 'Zona Oeste', 'baixa', 'positivo', 'parceria SENAI empregou desempregado',
 'resolvido', (now() - interval '28 days')::text, now() - interval '29 days'),

('5521976543211', 'Dirceu Fonseca',
 'Presidente do conselho comunitário da zona norte aqui. Temos 8 hectares de terreno público ocioso há 11 anos. Queremos propor ao deputado Matheus Braga a criação de um polo de logística e distribuição para gerar 500 empregos.',
 now() - interval '29 days 8 hours',
 'Desenvolvimento Econômico', 'Zona Norte', 'media', 'neutro', 'proposta polo logístico terreno público',
 'aberto', null, now() - interval '29 days 8 hours'),

('5521943218713', 'Sandra Mello',
 'Deputado Matheus Braga, minha filha de 19 anos caiu da bicicleta num buraco da ciclovia da Avenida das Flores na zona sul. Levou 8 pontos na cabeça. Já fotografei 14 trechos perigosos. O DER precisa ser acionado urgente.',
 now() - interval '30 days',
 'Infraestrutura & Obras', 'Zona Sul', 'alta', 'negativo', 'ciclovia destruída causou acidente',
 'em_andamento', null, now() - interval '30 days'),

('5521923456780', 'Simone Rodrigues',
 'Deputado Matheus, complementando a mensagem anterior sobre o plano de carreira: os professores estaduais vão entrar em greve na próxima segunda-feira se o projeto não for votado ainda esta semana. O senhor tem posição sobre isso?',
 now() - interval '30 days 6 hours',
 'Saúde & Educação', 'Centro', 'alta', 'negativo', 'greve professores anunciada segunda-feira',
 'aberto', null, now() - interval '30 days 6 hours'),

('5521934218758', 'Paulo Henrique',
 'Deputado Matheus Braga, atualização do caso do meu irmão Leandro: a defensoria entrou com habeas corpus depois da intervenção do gabinete e ele foi liberado ontem à noite. Estava preso injustamente há 6 meses. Muito obrigado.',
 now() - interval '31 days',
 'Segurança Pública', 'Zona Leste', 'baixa', 'positivo', 'habeas corpus liberou preso injusto',
 'resolvido', (now() - interval '30 days')::text, now() - interval '31 days');
